# 应用服务 WEB 访问端口
server:
  port: 8080

# MySQL Database Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  main:
    banner-mode: off

# MyBatis Configuration
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

### Log Configuration
logging:
  level:
    org.springframework.web: DEBUG
    com.demo.bookMange: DEBUG